version: "3"

services:
  database:
    image: mongo
    container_name: up_storage_mongo
    hostname: mongodb
    env_file:
      - .env
    ports:
      - 27017:${DB_PORT}
    volumes:
      - ./.docker/up_storage_mongo:/data/db
