export default {
	FETCH: '@post/FETCH',
	ASYNC_FETCH: '@post/ASYNC_FETCH',
	FETCH_ERROR: '@post/FETCH_ERROR',

	STORE: '@post/STORE',
	ASYNC_STORE: '@post/ASYNC_STORE',
	STORE_ERROR: '@post/STORE_ERROR',

	DELETE: '@post/DELETE',
	ASYNC_DELETE: '@post/ASYNC_DELETE',
	DELETE_ERROR: '@post/DELETE_ERROR',

	LOADING: '@post/LOADING',
}
