export default {
	FETCH: '@post/FETCH',
	FETCH_ERROR: '@post/FETCH_ERROR',

	STORE: '@post/STORE',
	STORE_ERROR: '@post/STORE_ERROR',

	DELETE: '@post/DELETE',
	DELETE_ERROR: '@post/DELETE_ERROR',

	PUSH_POSTS: '@post/PUSH_POSTS',
	UPDATE_SINGLE_POST: '@post/UPDATE_SINGLE_POST',
	LOADING: '@post/LOADING',
}
