const PostTypes = {
	FETCH_ALL_LOADING: '@post/FETCH_ALL_LOADING',
	FETCH_ALL: '@post/FETCH_ALL',
	FETCH_ALL_ERROR: '@post/FETCH_ALL_ERROR',

	STORE_LOADING: '@post/STORE_LOADING',
	STORE: '@post/STORE',
	STORE_ERROR: '@post/STORE_ERROR',

	DELETE_LOADING: '@post/DELETE_LOADING',
	DELETE: '@post/DELETE',
	DELETE_ERROR: '@post/DELETE_ERROR',

	PUSH_POSTS: '@post/PUSH_POSTS',
}

export default PostTypes
